### Demo na konferencję EuroHPC (case z kodowaniem binarnym i z QAOA) - draft
DO ZMIANY: opis 
We will focus on the following workflow instance (for now, in the simplified problem, we will not use the Workflow or WorkflowSchedulingProblem classes, because we want to test the Unbalanced Penalization method https://arxiv.org/pdf/2211.13914.pdf), which is not included in QHyper. But I will leave it here just for reference (especially for observation of what data is in the time and cost matrices).

In [18]:
import sys
sys.path.append("..")
from QHyper.problems.workflow_scheduling import (
    Workflow,
    WorkflowSchedulingProblem,
)

tasks_file =  "workflows_data/workflows/3_tasks_3_machines_1_path.json"
machines_file = "workflows_data/machines/machines_for_3_tasks_3_machines_1_path.json"
deadline = 13

workflow = Workflow(tasks_file, machines_file, deadline)
wsp = WorkflowSchedulingProblem(workflow)

In [19]:
wsp.workflow.cost_matrix

       MachineA  MachineB  MachineC
task1       6.0       8.0       8.0
task2       3.0       4.0       4.0
task3      12.0      16.0      16.0

Uwaga: tutaj tak naprawdę jest dodana jeszcze jedna maszyna (liczba maszyn musi być 2^n)

In [20]:
wsp.workflow.time_matrix

       MachineA  MachineB  MachineC
task1       6.0       2.0       4.0
task2       3.0       1.0       2.0
task3      12.0       4.0       8.0

Below is the list of the hyperparameters (weights) that can be changed.  I assumed that the weights hyper_b, hyper_c, hyper_d can be the same, since the constraint they represent has a very similar form.

In [21]:
hyper_params = {'cost_function_weight': 1, # weight for: cost function 
               'deadline_linear_form_weight': -2, # weight for: deadline constraint - linear form (-- this is from the unbalanced penalization approach)
                'deadline_quadratic_form_weight': 2} # weight for: deadline constraint - quadratic form

 DO ZMIANY: generacja tych wzorów z WFCommons

In [22]:
import numpy as np
import sympy
from sympy.core.expr import Expr

from QHyper.problems.base import Problem
from QHyper.util import Expression


class SimpleWorkflowProblem(Problem):

    
    def __init__(self) -> None:
        #uwaga: to jest na sztywno
        num_of_qubits = 6 #wsp.workflow.cost_matrix.shape[0] * wsp.workflow.cost_matrix.shape[1]
        self.variables = sympy.symbols(' '.join([f'x{i}' for i in range(num_of_qubits)]))                                  
        self._set_objective_function()
        self._set_constraints()
        
    def _set_objective_function(self) -> None:
        
        C_f = (6.0*(1-self.variables[0])*(1-self.variables[1]) 
        + 8.0*(1-self.variables[0])*(self.variables[1])  
        + 8.0*(self.variables[0])*(1-self.variables[1]) 
        + 2.0*(self.variables[0])*(self.variables[1])  
        + 3.0*(1-self.variables[2])*(1-self.variables[3]) 
        + 4.0*(1-self.variables[2])*(self.variables[3])  
        + 4.0*(self.variables[2])*(1-self.variables[3]) 
        + 1.0*(self.variables[2])*(self.variables[3])
        + 12.0*(1-self.variables[4])*(1-self.variables[5]) 
        + 16.0*(1-self.variables[4])*(self.variables[5])  
        + 16.0*(self.variables[4])*(1-self.variables[5]) 
        + 4.0*(self.variables[4])*(self.variables[5])  )
        
        self.deadline_aux=(6.0*(1-self.variables[0])*(1-self.variables[1]) 
       + 2.0*(1-self.variables[0])*(self.variables[1])  
        + 4.0*(self.variables[0])*(1-self.variables[1]) 
        + 16.0*(self.variables[0])*(self.variables[1])  
        + 3.0*(1-self.variables[2])*(1-self.variables[3]) 
        + 1.0*(1-self.variables[2])*(self.variables[3])  
        + 2.0*(self.variables[2])*(1-self.variables[3]) 
        + 8.0*(self.variables[2])*(self.variables[3])
        + 12.0*(1-self.variables[4])*(1-self.variables[5]) 
        + 4.0*(1-self.variables[4])*(self.variables[5])  
        + 8.0*(self.variables[4])*(1-self.variables[5]) 
        + 32.0*(self.variables[4])*(self.variables[5])  )

        K_f4_linear = deadline - self.deadline_aux
        K_f4_squared=K_f4_linear**2
        K_f4_squared1=sympy.expand(K_f4_squared)

       # print(K_f4_squared1, "\n\n")
          
        for i in range(6):
            K_f4_squared1=K_f4_squared1.subs(self.variables[i]**2, self.variables[i])
        #print(K_f4_squared1,"\n\n")  
        
       # print(K_f4_squared1)     
        self.objective_function = (Expression(hyper_params['cost_function_weight'] * C_f 
                                              + hyper_params['deadline_linear_form_weight'] *  K_f4_linear
                                   + hyper_params['deadline_quadratic_form_weight'] * K_f4_linear**2))
        
    def _set_constraints(self):
       # print(self.deadline_aux)

        
      
            
        self.constraints = []
    
    def get_score(self, result, penalty=0):
        
        x = [int(val) for val in result]
    
        if (6.0*(1.0-x[0])*(1-x[1]) 
        + 2.0*(1.0-x[0])*(x[1])  
        + 4.0*(x[0])*(1.0-x[1]) 
        + 16.0*(x[0])*(x[1])  
        + 3.0*(1.0-x[2])*(1.0-x[3]) 
        + 1.0*(1.0-x[2])*(x[3])  
        + 2.0*(x[2])*(1.0-x[3]) 
        + 8.0*(x[2])*(x[3])
        + 12.0*(1.0-x[4])*(1.0-x[5]) 
        + 4.0*(1.0-x[4])*(x[5])  
        + 8.0*(x[4])*(1.0-x[5]) 
        + 32.0*(x[4])*(x[5]) <=13 ):
            
            return (6.0*(1.0-x[0])*(1.0-x[1]) 
        + 8.0*(1.0-x[0])*(x[1])  
        + 8.0*(x[0])*(1.0-x[1]) 
        + 2.0*(x[0])*(x[1])  
        + 3.0*(1.0-x[2])*(1.0-x[3]) 
        + 4.0*(1.0-x[2])*(x[3])  
        + 4.0*(x[2])*(1.0-x[3]) 
        + 1.0*(x[2])*(x[3])
        + 12.0*(1.0-x[4])*(1.0-x[5]) 
        + 16.0*(1.0-x[4])*(x[5])  
        + 16.0*(x[4])*(1.0-x[5]) 
        + 4.0*(x[4])*(x[5]) ) 
        
        return penalty

In [23]:
problem = SimpleWorkflowProblem()

In [24]:
print(f"Variables used to describe objective function"
      f" and constraints: {problem.variables}")
print(f"Objective function: {problem.objective_function}")
print("Constraints (RHS == 0):")
for constraint in problem.constraints:
    print(f"    {constraint}")

Variables used to describe objective function and constraints: (x0, x1, x2, x3, x4, x5)
Objective function: {('x0', 'x0', 'x1', 'x1'): 512.0, ('x0', 'x0', 'x1'): -128.0, ('x0', 'x0'): 8.0, ('x0', 'x1', 'x1'): -256.0, ('x0', 'x1', 'x2', 'x3'): 512.0, ('x0', 'x1', 'x2'): -64.0, ('x0', 'x1', 'x3'): -128.0, ('x0', 'x1', 'x4', 'x5'): 2048.0, ('x0', 'x1', 'x4'): -256.0, ('x0', 'x1', 'x5'): -512.0, ('x0', 'x1'): 568.0, ('x0', 'x2', 'x3'): -64.0, ('x0', 'x2'): 8.0, ('x0', 'x3'): 16.0, ('x0', 'x4', 'x5'): -256.0, ('x0', 'x4'): 32.0, ('x0', 'x5'): 64.0, ('x0',): -66.0, ('x1', 'x1'): 32.0, ('x1', 'x2', 'x3'): -128.0, ('x1', 'x2'): 16.0, ('x1', 'x3'): 32.0, ('x1', 'x4', 'x5'): -512.0, ('x1', 'x4'): 64.0, ('x1', 'x5'): 128.0, ('x1',): -134.0, ('x2', 'x2', 'x3', 'x3'): 128.0, ('x2', 'x2', 'x3'): -32.0, ('x2', 'x2'): 2.0, ('x2', 'x3', 'x3'): -64.0, ('x2', 'x3', 'x4', 'x5'): 1024.0, ('x2', 'x3', 'x4'): -128.0, ('x2', 'x3', 'x5'): -256.0, ('x2', 'x3'): 276.0, ('x2', 'x4', 'x5'): -128.0, ('x2', 'x4'): 16.0, ('x2', 'x5'): 32.0, ('x2',): -33.0, ('x3', 'x3'): 8.0, ('x3', 'x4', 'x5'): -256.0, ('x3', 'x4'): 32.0, ('x3', 'x5'): 64.0, ('x3',): -67.0, ('x4', 'x4', 'x5', 'x5'): 2048.0, ('x4', 'x4', 'x5'): -512.0, ('x4', 'x4'): 32.0, ('x4', 'x5', 'x5'): -1024.0, ('x4', 'x5'): 1200.0, ('x4',): -132.0, ('x5', 'x5'): 128.0, ('x5',): -268.0, (): 165.0}
Constraints (RHS == 0):

# 3 Using QHyper

Do zmiany - konfiguracja wag

In [25]:
params_config = {
        'angles': [[0.1e-13]*6, [np.pi/2]*6], # QAOA angles - first we have gammas (for the cost Hamiltonian), then we have betas (for the mixer)
        'hyper_args': [1, # do not change - this should be the weight for the 'cost function' but since in our cost function 
                          # we also have the deadline in the linear form (as of now it needs to be implemented this way due to QHyper limitations)
                          # the weight for the actual cost function is set there. THIS WILL NOT WORK WELL WITH HYPER-QAOA.
                          
                       ],
    }

In [26]:
# Simple quantum circuit without optimzers will be used to test the results
# WF-QAOA is choosen becasue this PQC has most suitable evaluation function
#DO ZMIANY: nowe API QHyper
from QHyper.solvers.vqa.base import VQA
tester_config = {
    'pqc': {
        'type': 'wfqaoa',
        'layers': 6,
    }
}

tester = VQA(problem, config=tester_config)

In [27]:
# Create a VQA instance with QAOA as PQC and scipy optimizer
# This can be done in two various way
# 1. Providing dict with config (usefull to save experiment confing in e.g JSON)
# DO ZMIANY sqaoa -> qaoa (backend= "default.qubit") oraz QNG optimiser (krok 0.0001) 50 krokow
solver_config = {
    'pqc': {
        'type': 'hoboqaoa',
        'layers': 6
    }
}
vqa = VQA(problem, config=solver_config)

In [28]:
# DO ZMIANY vqa.solve() UWAGA !!!: tutaj dobrze, żeby te wyniki wypisywały się "na żywo" przy ustawieniu odpowiedniej flagi, 
#to jest potrzebne do monitorowania, czy optymalizator w ogóle działa przy wykonywaniu eksperymentów (w razie gdyby za bardzo skakał 
# można przerwać i zmienić krok, a nie czekać wszystkie kroki.
#na filmie przytnie się  tę część,
best_params, history = vqa.evaluate(params_config)

1   612.9999999999897   [[ 1.00002336e-14  1.00000329e-14  1.00001557e-14  1.00000197e-14
   1.00000778e-14  1.00000066e-14]
 [-1.31408691e+02 -6.47801878e+01 -7.54907515e+01 -5.95615710e+01
  -6.65688680e+01 -6.07282193e+01]]

2   612.9999999919736   [[-8.09993855e-05  1.61575657e-04  2.82250669e-06 -6.84838499e-06
   6.50844387e-06  2.65478041e-05]
 [-2.51305635e+02 -1.22819925e+02 -1.20625443e+02 -9.46081223e+01
  -9.88494452e+01 -8.18867592e+01]]

3   500.2934557003054   [[ 6.34410997e-05  3.04391517e-04  7.36566972e-05 -1.14022297e-05
   1.59005622e-05  1.29970759e-04]
 [-2.51356669e+02 -1.22758311e+02 -1.20585628e+02 -9.45842183e+01
  -9.88315525e+01 -8.19852366e+01]]

4   208.1912732111584   [[ 1.04263604e-04  3.45062896e-04  1.01253997e-04 -4.21443414e-06
   2.88791589e-05  1.68651404e-04]
 [-2.51362067e+02 -1.22765510e+02 -1.20598079e+02 -9.45975698e+01
  -9.88441297e+01 -8.19982886e+01]]

5   177.73599343318492   [[ 1.13948330e-04  3.54874198e-04  1.24524429e-04 -1.33566583e-06
   4.08752465e-05  1.86147812e-04]
 [-2.51368229e+02 -1.22762934e+02 -1.20595276e+02 -9.45949796e+01
  -9.88413584e+01 -8.19955686e+01]]

6   171.38603295243513   [[ 1.17239594e-04  3.56733991e-04  1.40567440e-04  3.96824119e-06
   5.22715324e-05  1.94379796e-04]
 [-2.51408562e+02 -1.22766487e+02 -1.20596370e+02 -9.45961471e+01
  -9.88425904e+01 -8.19945759e+01]]

7   166.1401849860502   [[ 1.21020130e-04  3.57505722e-04  1.58707432e-04  8.18756314e-06
   6.35683373e-05  2.03912869e-04]
 [-2.51458375e+02 -1.22769062e+02 -1.20595946e+02 -9.45957170e+01
  -9.88423368e+01 -8.19922096e+01]]

8   159.34381784367747   [[ 1.27749319e-04  3.58643626e-04  1.78118411e-04  1.21805476e-05
   7.48121137e-05  2.14782892e-04]
 [-2.51514949e+02 -1.22771690e+02 -1.20595249e+02 -9.45949380e+01
  -9.88418919e+01 -8.19896931e+01]]

9   151.1541278057249   [[ 1.38309020e-04  3.60902789e-04  1.98172639e-04  1.61771773e-05
   8.60067608e-05  2.26919565e-04]
 [-2.51564891e+02 -1.22774096e+02 -1.20594272e+02 -9.45937951e+01
  -9.88413076e+01 -8.19872543e+01]]

10   143.0212591340686   [[ 1.51545611e-04  3.63911997e-04  2.17403290e-04  2.04811744e-05
   9.70601370e-05  2.38966920e-04]
 [-2.51599129e+02 -1.22776394e+02 -1.20593112e+02 -9.45923852e+01
  -9.88407243e+01 -8.19850018e+01]]

11   136.14514902050013   [[ 1.65739036e-04  3.66874525e-04  2.34871121e-04  2.51985866e-05
   1.07880683e-04  2.49718916e-04]
 [-2.51619306e+02 -1.22778858e+02 -1.20591848e+02 -9.45908055e+01
  -9.88402153e+01 -8.19828666e+01]]

12   130.5843657411331   [[ 1.79816517e-04  3.69369675e-04  2.50478117e-04  3.02642867e-05
   1.18433170e-04  2.58842912e-04]
 [-2.51630670e+02 -1.22781572e+02 -1.20590504e+02 -9.45890989e+01
  -9.88397734e+01 -8.19807636e+01]]

13   125.99662167972474   [[ 1.93270633e-04  3.71362599e-04  2.64460560e-04  3.55845377e-05
   1.28717420e-04  2.66503224e-04]
 [-2.51637006e+02 -1.22784431e+02 -1.20589087e+02 -9.45872878e+01
  -9.88393820e+01 -8.19786800e+01]]

14   122.11471268366213   [[ 2.05881154e-04  3.72956628e-04  2.77065342e-04  4.10916502e-05
   1.38743072e-04  2.72963389e-04]
 [-2.51640478e+02 -1.22787304e+02 -1.20587625e+02 -9.45854089e+01
  -9.88390511e+01 -8.19766548e+01]]

15   118.77880681796246   [[ 2.17558120e-04  3.74264336e-04  2.88484777e-04  4.67372855e-05
   1.48521403e-04  2.78455874e-04]
 [-2.51642284e+02 -1.22790083e+02 -1.20586149e+02 -9.45834983e+01
  -9.88387967e+01 -8.19747331e+01]]

16   115.8899932425619   [[ 2.28277849e-04  3.75371024e-04  2.98861594e-04  5.24840115e-05
   1.58063465e-04  2.83159035e-04]
 [-2.51643107e+02 -1.22792695e+02 -1.20584684e+02 -9.45815846e+01
  -9.88386298e+01 -8.19729487e+01]]

17   113.37865012715939   [[ 2.38054693e-04  3.76333340e-04  3.08305036e-04  5.83008424e-05
   1.67379921e-04  2.87204959e-04]
 [-2.51643350e+02 -1.22795104e+02 -1.20583247e+02 -9.45796875e+01
  -9.88385544e+01 -8.19713206e+01]]

18   111.18940684162796   [[ 2.46926297e-04  3.77186759e-04  3.16903714e-04  6.41613024e-05
   1.76481124e-04  2.90692118e-04]
 [-2.51643258e+02 -1.22797294e+02 -1.20581849e+02 -9.45778196e+01
  -9.88385686e+01 -8.19698560e+01]]

19   109.27504013530327   [[ 2.54944451e-04  3.77953174e-04  3.24733766e-04  7.00425414e-05
   1.85377130e-04  2.93695993e-04]
 [-2.51642985e+02 -1.22799266e+02 -1.20580496e+02 -9.45759886e+01
  -9.88386669e+01 -8.19685537e+01]]

20   107.59428752414208   [[ 2.62168852e-04  3.78646479e-04  3.31863445e-04  7.59248366e-05
   1.94077647e-04  2.96276610e-04]
 [-2.51642626e+02 -1.22801031e+02 -1.20579190e+02 -9.45741986e+01
  -9.88388417e+01 -8.19674071e+01]]

21   106.11110987558149   [[ 2.68662706e-04  3.79276165e-04  3.38355465e-04  8.17912239e-05
   2.02591932e-04  2.98483510e-04]
 [-2.51642240e+02 -1.22802605e+02 -1.20577932e+02 -9.45724513e+01
  -9.88390845e+01 -8.19664066e+01]]

22   104.79435240935409   [[ 2.74489654e-04  3.79849432e-04  3.44268074e-04  8.76271765e-05
   2.10928706e-04  3.00358889e-04]
 [-2.51641866e+02 -1.22804006e+02 -1.20576722e+02 -9.45707470e+01
  -9.88393866e+01 -8.19655410e+01]]

23   103.61742532144333   [[ 2.79711686e-04  3.80372346e-04  3.49655503e-04  9.34203115e-05
   2.19096090e-04  3.01939546e-04]
 [-2.51641525e+02 -1.22805252e+02 -1.20575558e+02 -9.45690850e+01
  -9.88397397e+01 -8.19647987e+01]]

24   102.55791027414882   [[ 2.84387803e-04  3.80850416e-04  3.54568114e-04  9.91601241e-05
   2.27101562e-04  3.03258084e-04]
 [-2.51641230e+02 -1.22806360e+02 -1.20574439e+02 -9.45674642e+01
  -9.88401359e+01 -8.19641684e+01]]

25   101.59710320471396   [[ 2.88573218e-04  3.81288844e-04  3.59052465e-04  1.04837749e-04
   2.34951946e-04  3.04343674e-04]
 [-2.51640987e+02 -1.22807348e+02 -1.20573361e+02 -9.45658828e+01
  -9.88405682e+01 -8.19636391e+01]]

26   100.71953074486184   [[ 2.92318953e-04  3.81692608e-04  3.63151372e-04  1.10445751e-04
   2.42653431e-04  3.05222541e-04]
 [-2.51640799e+02 -1.22808229e+02 -1.20572324e+02 -9.45643393e+01
  -9.88410301e+01 -8.19632006e+01]]

27   99.91247519119078   [[ 2.95671711e-04  3.82066463e-04  3.66904005e-04  1.15977941e-04
   2.50211589e-04  3.05918314e-04]
 [-2.51640665e+02 -1.22809017e+02 -1.20571325e+02 -9.45628318e+01
  -9.88415160e+01 -8.19628435e+01]]

28   99.16553232681366   [[ 2.98673924e-04  3.82414916e-04  3.70346020e-04  1.21429218e-04
   2.57631422e-04  3.06452283e-04]
 [-2.51640582e+02 -1.22809724e+02 -1.20570361e+02 -9.45613586e+01
  -9.88420207e+01 -8.19625591e+01]]

29   98.4702156467704   [[ 3.01363926e-04  3.82742190e-04  3.73509744e-04  1.26795426e-04
   2.64917408e-04  3.06843614e-04]
 [-2.51640549e+02 -1.22810360e+02 -1.20569432e+02 -9.45599180e+01
  -9.88425398e+01 -8.19623397e+01]]

30   97.8196122515004   [[ 3.03776192e-04  3.83052198e-04  3.76424366e-04  1.32073243e-04
   2.72073548e-04  3.07109532e-04]
 [-2.51640560e+02 -1.22810934e+02 -1.20568534e+02 -9.45585084e+01
  -9.88430694e+01 -8.19621782e+01]]

31   97.20809013783165   [[ 3.05941620e-04  3.83348526e-04  3.79116163e-04  1.37260066e-04
   2.79103422e-04  3.07265487e-04]
 [-2.51640613e+02 -1.22811454e+02 -1.20567666e+02 -9.45571284e+01
  -9.88436061e+01 -8.19620684e+01]]

32   96.63105335052298   [[ 3.07887819e-04  3.83634428e-04  3.81608722e-04  1.42353928e-04
   2.86010235e-04  3.07325310e-04]
 [-2.51640703e+02 -1.22811927e+02 -1.20566827e+02 -9.45557765e+01
  -9.88441468e+01 -8.19620045e+01]]

33   96.08473982223822   [[ 3.09639409e-04  3.83912826e-04  3.83923166e-04  1.47353413e-04
   2.92796866e-04  3.07301359e-04]
 [-2.51640826e+02 -1.22812359e+02 -1.20566015e+02 -9.45544516e+01
  -9.88446891e+01 -8.19619815e+01]]

34   95.56605616563512   [[ 3.11218300e-04  3.84186324e-04  3.86078376e-04  1.52257590e-04
   2.99465914e-04  3.07204653e-04]
 [-2.51640980e+02 -1.22812756e+02 -1.20565228e+02 -9.45531525e+01
  -9.88452307e+01 -8.19619948e+01]]

35   95.07244376464942   [[ 3.12643962e-04  3.84457216e-04  3.88091198e-04  1.57065946e-04
   3.06019736e-04  3.07045000e-04]
 [-2.51641161e+02 -1.22813121e+02 -1.20564466e+02 -9.45518782e+01
  -9.88457697e+01 -8.19620404e+01]]

36   94.60177094918406   [[ 3.13933677e-04  3.84727514e-04  3.89976643e-04  1.61778338e-04
   3.12460483e-04  3.06831114e-04]
 [-2.51641365e+02 -1.22813460e+02 -1.20563726e+02 -9.45506276e+01
  -9.88463046e+01 -8.19621147e+01]]

37   94.15224663725452   [[ 3.15102766e-04  3.84998960e-04  3.91748071e-04  1.66394938e-04
   3.18790136e-04  3.06570725e-04]
 [-2.51641591e+02 -1.22813775e+02 -1.20563008e+02 -9.45494000e+01
  -9.88468338e+01 -8.19622144e+01]]

38   93.72235147399348   [[ 3.16164802e-04  3.85273051e-04  3.93417361e-04  1.70916195e-04
   3.25010532e-04  3.06270678e-04]
 [-2.51641835e+02 -1.22814070e+02 -1.20562311e+02 -9.45481946e+01
  -9.88473563e+01 -8.19623366e+01]]

39   93.3107831209717   [[ 3.17131800e-04  3.85551063e-04  3.94995066e-04  1.75342794e-04
   3.31123389e-04  3.05937030e-04]
 [-2.51642094e+02 -1.22814348e+02 -1.20561634e+02 -9.45470106e+01
  -9.88478710e+01 -8.19624787e+01]]

40   92.9164129176083   [[ 3.18014388e-04  3.85834069e-04  3.96490559e-04  1.79675625e-04
   3.37130332e-04  3.05575125e-04]
 [-2.51642368e+02 -1.22814610e+02 -1.20560975e+02 -9.45458474e+01
  -9.88483772e+01 -8.19626386e+01]]

41   92.53825163470772   [[ 3.18821962e-04  3.86122962e-04  3.97912156e-04  1.83915749e-04
   3.43032903e-04  3.05189681e-04]
 [-2.51642653e+02 -1.22814859e+02 -1.20560334e+02 -9.45447045e+01
  -9.88488742e+01 -8.19628140e+01]]

42   92.17542246582968   [[ 3.19562825e-04  3.86418470e-04  3.99267235e-04  1.88064376e-04
   3.48832587e-04  3.04784851e-04]
 [-2.51642949e+02 -1.22815097e+02 -1.20559710e+02 -9.45435814e+01
  -9.88493615e+01 -8.19630032e+01]]

43   91.82713975916593   [[ 3.20244311e-04  3.86721183e-04  4.00562341e-04  1.92122837e-04
   3.54530820e-04  3.04364288e-04]
 [-2.51643254e+02 -1.22815326e+02 -1.20559102e+02 -9.45424774e+01
  -9.88498386e+01 -8.19632046e+01]]

44   91.49269228782127   [[ 3.20872895e-04  3.87031560e-04  4.01803280e-04  1.96092566e-04
   3.60128997e-04  3.03931201e-04]
 [-2.51643565e+02 -1.22815547e+02 -1.20558510e+02 -9.45413922e+01
  -9.88503053e+01 -8.19634166e+01]]

45   91.17143009805338   [[ 3.21454291e-04  3.87349950e-04  4.02995200e-04  1.99975080e-04
   3.65628490e-04  3.03488407e-04]
 [-2.51643883e+02 -1.22815760e+02 -1.20557932e+02 -9.45403253e+01
  -9.88507611e+01 -8.19636380e+01]]

46   90.86275417116588   [[ 3.21993541e-04  3.87676604e-04  4.04142667e-04  2.03771961e-04
   3.71030646e-04  3.03038373e-04]
 [-2.51644206e+02 -1.22815969e+02 -1.20557369e+02 -9.45392765e+01
  -9.88512061e+01 -8.19638677e+01]]

47   90.56610829295758   [[ 3.22495091e-04  3.88011691e-04  4.05249735e-04  2.07484846e-04
   3.76336802e-04  3.02583257e-04]
 [-2.51644533e+02 -1.22816172e+02 -1.20556819e+02 -9.45382452e+01
  -9.88516400e+01 -8.19641045e+01]]

48   90.28097265151987   [[ 3.22962863e-04  3.88355305e-04  4.06320000e-04  2.11115410e-04
   3.81548280e-04  3.02124945e-04]
 [-2.51644863e+02 -1.22816372e+02 -1.20556281e+02 -9.45372312e+01
  -9.88520629e+01 -8.19643476e+01]]

49   90.00685878555359   [[ 3.23400312e-04  3.88707476e-04  4.07356656e-04  2.14665356e-04
   3.86666400e-04  3.01665080e-04]
 [-2.51645196e+02 -1.22816568e+02 -1.20555756e+02 -9.45362341e+01
  -9.88524746e+01 -8.19645961e+01]]

50   89.74330558602831   [[ 3.23810485e-04  3.89068182e-04  4.08362541e-04  2.18136406e-04
   3.91692476e-04  3.01205096e-04]
 [-2.51645530e+02 -1.22816763e+02 -1.20555243e+02 -9.45352537e+01
  -9.88528753e+01 -8.19648493e+01]]

In [12]:
history.plot(x='step_no', y='cost', kind="scatter")

In [13]:
# DO ZMIANY - nowe api do wyników
best_results = tester.evaluate(best_params,print_results=True)
print(f"Best results: {best_results}")
print(f"Params used for optimizer:\n{best_params['angles']},\n"
      f"and params used for hyperoptimizer: {best_params['hyper_args']}")

In [15]:
#bp={'angles': ([[ 3.23810485e-04,  3.89068182e-04,  4.08362541e-04,
      #    2.18136406e-04,  3.91692476e-04,  3.01205096e-04],
     #   [-2.51645530e+02, -1.22816763e+02, -1.20555243e+02,
      #   -9.45352537e+01, -9.88528753e+01, -8.19648493e+01]]), 'hyper_args': [1]}

In [16]:
#bp={'angles':([[0.1e-13]*6, [np.pi/2]*6]), 'hyper_args': [1]}

In [17]:
#best_results = tester.evaluate(bp, print_results=True)
#print(f"Best results: {best_results}")

tutaj
  (-256.0) [Zx0]
+ (257.0) [Ix0]
  (-192.0) [Zx0]
+ (193.0) [Ix0]
  (-196.0) [Zx0]
+ (197.0) [Ix0]
  (-68.0) [Zx0]
+ (69.0) [Ix0]
  (-324.0) [Zx0]
+ (325.0) [Ix0]
  (-292.0) [Zx0]
+ (293.0) [Ix0]
  (-228.0) [Zx0]
+ (229.0) [Ix0]
  (-1252.0) [Zx0]
+ (1253.0) [Ix0]
  (-1124.0) [Zx0]
+ (1125.0) [Ix0]
  (-868.0) [Zx0]
+ (869.0) [Ix0]
  (-1010.0) [Zx0]
+ (-142.0) [Zx1]
+ (1011.0) [Ix0]
+ (142.0) [Zx0 Zx1]
  (-978.0) [Zx0]
+ (-142.0) [Zx1]
+ (979.0) [Ix0]
+ (142.0) [Zx0 Zx1]
  (-980.0) [Zx0]
+ (-142.0) [Zx1]
+ (-2.0) [Zx2]
+ (981.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (142.0) [Zx0 Zx1]
  (-984.0) [Zx0]
+ (-142.0) [Zx1]
+ (-4.0) [Zx3]
+ (-2.0) [Zx2]
+ (985.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (142.0) [Zx0 Zx1]
  (-856.0) [Zx0]
+ (-142.0) [Zx1]
+ (-4.0) [Zx3]
+ (-2.0) [Zx2]
+ (857.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (142.0) [Zx0 Zx1]
  (-864.0) [Zx0]
+ (-142.0) [Zx1]
+ (-8.0) [Zx4]
+ (-4.0) [Zx3]
+ (-2.0) [Zx2]
+ (865.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (8.0) [Zx0 Zx4]
+ (142.0) [Zx0 Zx1]
  (-880.0) [Zx0]
+ (-142.0) [Zx1]
+ (-16.0) [Zx5]
+ (-8.0) [Zx4]
+ (-4.0) [Zx3]
+ (-2.0) [Zx2]
+ (881.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (8.0) [Zx0 Zx4]
+ (16.0) [Zx0 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-142.0) [Zx1]
+ (-16.0) [Zx5]
+ (-8.0) [Zx4]
+ (-4.0) [Zx3]
+ (-2.0) [Zx2]
+ (848.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (8.0) [Zx0 Zx4]
+ (16.0) [Zx0 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-158.0) [Zx1]
+ (-16.0) [Zx5]
+ (-8.0) [Zx4]
+ (-4.0) [Zx3]
+ (-2.0) [Zx2]
+ (864.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (8.0) [Zx0 Zx4]
+ (16.0) [Zx0 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-94.0) [Zx1]
+ (-16.0) [Zx5]
+ (-8.0) [Zx4]
+ (-4.0) [Zx3]
+ (-2.0) [Zx2]
+ (800.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (8.0) [Zx0 Zx4]
+ (16.0) [Zx0 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-98.0) [Zx1]
+ (-16.0) [Zx5]
+ (-8.0) [Zx4]
+ (-6.0) [Zx2]
+ (-4.0) [Zx3]
+ (804.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (16.0) [Zx0 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-106.0) [Zx1]
+ (-16.0) [Zx5]
+ (-12.0) [Zx3]
+ (-8.0) [Zx4]
+ (-6.0) [Zx2]
+ (812.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-16.0) [Zx5]
+ (-12.0) [Zx3]
+ (-8.0) [Zx4]
+ (-6.0) [Zx2]
+ (150.0) [Zx1]
+ (556.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-24.0) [Zx4]
+ (-16.0) [Zx5]
+ (-12.0) [Zx3]
+ (-6.0) [Zx2]
+ (134.0) [Zx1]
+ (572.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (-12.0) [Zx3]
+ (-6.0) [Zx2]
+ (102.0) [Zx1]
+ (604.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (-12.0) [Zx3]
+ (-6.0) [Zx2]
+ (169.0) [Zx1]
+ (537.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-70.0) [Zx2]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (-12.0) [Zx3]
+ (169.0) [Zx1]
+ (601.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-54.0) [Zx2]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (-12.0) [Zx3]
+ (169.0) [Zx1]
+ (585.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-55.0) [Zx2]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (-12.0) [Zx3]
+ (169.0) [Zx1]
+ (586.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (-23.0) [Zx2]
+ (-12.0) [Zx3]
+ (169.0) [Zx1]
+ (554.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-535.0) [Zx2]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (-12.0) [Zx3]
+ (169.0) [Zx1]
+ (1066.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-471.0) [Zx2]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (-12.0) [Zx3]
+ (169.0) [Zx1]
+ (1002.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-343.0) [Zx2]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (-12.0) [Zx3]
+ (169.0) [Zx1]
+ (874.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-412.0) [Zx2]
+ (-81.0) [Zx3]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (169.0) [Zx1]
+ (943.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-348.0) [Zx2]
+ (-81.0) [Zx3]
+ (-48.0) [Zx5]
+ (-24.0) [Zx4]
+ (169.0) [Zx1]
+ (879.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-352.0) [Zx2]
+ (-81.0) [Zx3]
+ (-48.0) [Zx5]
+ (-28.0) [Zx4]
+ (169.0) [Zx1]
+ (883.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-360.0) [Zx2]
+ (-81.0) [Zx3]
+ (-56.0) [Zx5]
+ (-28.0) [Zx4]
+ (169.0) [Zx1]
+ (891.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-343.5) [Zx2]
+ (-81.0) [Zx3]
+ (-56.0) [Zx5]
+ (-28.0) [Zx4]
+ (169.0) [Zx1]
+ (874.5) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-343.5) [Zx2]
+ (-85.0) [Zx3]
+ (-56.0) [Zx5]
+ (-28.0) [Zx4]
+ (169.0) [Zx1]
+ (878.5) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-343.5) [Zx2]
+ (-56.0) [Zx5]
+ (-28.0) [Zx4]
+ (43.0) [Zx3]
+ (169.0) [Zx1]
+ (750.5) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-343.5) [Zx2]
+ (-56.0) [Zx5]
+ (-36.0) [Zx4]
+ (35.0) [Zx3]
+ (169.0) [Zx1]
+ (758.5) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-343.5) [Zx2]
+ (-72.0) [Zx5]
+ (-36.0) [Zx4]
+ (19.0) [Zx3]
+ (169.0) [Zx1]
+ (774.5) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (16.0) [Zx3 Zx5]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-343.5) [Zx2]
+ (-72.0) [Zx5]
+ (-36.0) [Zx4]
+ (52.5) [Zx3]
+ (169.0) [Zx1]
+ (741.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (16.0) [Zx3 Zx5]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-1060.0) [Zx4]
+ (-847.0) [Zx0]
+ (-343.5) [Zx2]
+ (-72.0) [Zx5]
+ (52.5) [Zx3]
+ (169.0) [Zx1]
+ (1765.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (16.0) [Zx3 Zx5]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-804.0) [Zx4]
+ (-343.5) [Zx2]
+ (-72.0) [Zx5]
+ (52.5) [Zx3]
+ (169.0) [Zx1]
+ (1509.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (16.0) [Zx3 Zx5]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-820.0) [Zx4]
+ (-343.5) [Zx2]
+ (-72.0) [Zx5]
+ (52.5) [Zx3]
+ (169.0) [Zx1]
+ (1525.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (16.0) [Zx3 Zx5]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-343.5) [Zx2]
+ (-308.0) [Zx4]
+ (-72.0) [Zx5]
+ (52.5) [Zx3]
+ (169.0) [Zx1]
+ (1013.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (16.0) [Zx3 Zx5]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
  (-847.0) [Zx0]
+ (-608.0) [Zx4]
+ (-372.0) [Zx5]
+ (-343.5) [Zx2]
+ (52.5) [Zx3]
+ (169.0) [Zx1]
+ (1313.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (16.0) [Zx3 Zx5]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
+ (300.0) [Zx4 Zx5]
  (-847.0) [Zx0]
+ (-542.0) [Zx4]
+ (-372.0) [Zx5]
+ (-343.5) [Zx2]
+ (52.5) [Zx3]
+ (169.0) [Zx1]
+ (1247.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (16.0) [Zx3 Zx5]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
+ (300.0) [Zx4 Zx5]
  (-847.0) [Zx0]
+ (-542.0) [Zx4]
+ (-436.0) [Zx5]
+ (-343.5) [Zx2]
+ (52.5) [Zx3]
+ (169.0) [Zx1]
+ (1311.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (16.0) [Zx3 Zx5]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
+ (300.0) [Zx4 Zx5]
  (-847.0) [Zx0]
+ (-542.0) [Zx4]
+ (-343.5) [Zx2]
+ (-302.0) [Zx5]
+ (52.5) [Zx3]
+ (169.0) [Zx1]
+ (1177.0) [Ix0]
+ (2.0) [Zx0 Zx2]
+ (4.0) [Zx0 Zx3]
+ (4.0) [Zx1 Zx2]
+ (4.0) [Zx2 Zx4]
+ (8.0) [Zx0 Zx4]
+ (8.0) [Zx1 Zx3]
+ (8.0) [Zx2 Zx5]
+ (8.0) [Zx3 Zx4]
+ (16.0) [Zx0 Zx5]
+ (16.0) [Zx1 Zx4]
+ (16.0) [Zx3 Zx5]
+ (32.0) [Zx1 Zx5]
+ (69.0) [Zx2 Zx3]
+ (142.0) [Zx0 Zx1]
+ (300.0) [Zx4 Zx5]
[0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625
 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625
 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625
 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625
 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625
 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625
 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625
 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625 0.015625]
bla 000000, 0.01562, 0
bla 000001, 0.01562, 25.0
bla 000010, 0.01562, 0
bla 000011, 0.01562, 0
bla 000100, 0.01562, 0
bla 000101, 0.01562, 26.0
bla 000110, 0.01562, 0
bla 000111, 0.01562, 0
bla 001000, 0.01562, 0
bla 001001, 0.01562, 26.0
bla 001010, 0.01562, 0
bla 001011, 0.01562, 0
bla 001100, 0.01562, 0
bla 001101, 0.01562, 0
bla 001110, 0.01562, 0
bla 001111, 0.01562, 0
bla 010000, 0.01562, 0
bla 010001, 0.01562, 27.0
bla 010010, 0.01562, 27.0
bla 010011, 0.01562, 0
bla 010100, 0.01562, 0
bla 010101, 0.01562, 28.0
bla 010110, 0.01562, 28.0
bla 010111, 0.01562, 0
bla 011000, 0.01562, 0
bla 011001, 0.01562, 28.0
bla 011010, 0.01562, 28.0
bla 011011, 0.01562, 0
bla 011100, 0.01562, 0
bla 011101, 0.01562, 0
bla 011110, 0.01562, 0
bla 011111, 0.01562, 0
bla 100000, 0.01562, 0
bla 100001, 0.01562, 27.0
bla 100010, 0.01562, 0
bla 100011, 0.01562, 0
bla 100100, 0.01562, 0
bla 100101, 0.01562, 28.0
bla 100110, 0.01562, 28.0
bla 100111, 0.01562, 0
bla 101000, 0.01562, 0
bla 101001, 0.01562, 28.0
bla 101010, 0.01562, 0
bla 101011, 0.01562, 0
bla 101100, 0.01562, 0
bla 101101, 0.01562, 0
bla 101110, 0.01562, 0
bla 101111, 0.01562, 0
bla 110000, 0.01562, 0
bla 110001, 0.01562, 0
bla 110010, 0.01562, 0
bla 110011, 0.01562, 0
bla 110100, 0.01562, 0
bla 110101, 0.01562, 0
bla 110110, 0.01562, 0
bla 110111, 0.01562, 0
bla 111000, 0.01562, 0
bla 111001, 0.01562, 0
bla 111010, 0.01562, 0
bla 111011, 0.01562, 0
bla 111100, 0.01562, 0
bla 111101, 0.01562, 0
bla 111110, 0.01562, 0
bla 111111, 0.01562, 0
Best results: 5.5312499999999964